declare type subjectsEnumT =
	| 'Math'
	| 'Science'
	| 'English'
	| 'History'
	| 'Islamic Studies'
	| 'Art'
	| 'Music'
	| 'Physical Education'
	| 'Computer Science'
	| 'Social Studies'
	| 'Arabic'
	| 'French'
	| 'German'
	| 'Spanish';
